spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pfe2025
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true
  mail:
    host: 127.0.0.1
    port: 1025
    username: nizarouertani9@protonmail.com
    password: RbdiLSV64u0
    # password: RbdiLSV64u0_90CEV7dlpg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: false
          ssl:
            enable: false
            trust: "*"
            checkserveridentity: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000

# Email configuration
email:
  from: nizarouertani9@protonmail.com

application:
  security:
    jwtSecret: I12OI3N12IONOIEN12IONEIO12JOI312KLNEOKZAKLHEIHO21IN3KL1N2LKNDIOI12OI3N12IONOIEN12IONEIO12JOI312KL
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 8640000

logging:
  level:
    org.springframework.security.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN

upload:
  dir: classpath:/assets/images

# Stripe Configuration
stripe:
  secret:
    key: sk_test_51RXlPKQ6JcV4ZCjFQbwDeEqDlhyMyukOGkpDcr8ZXONpc3V8DTUVCNWRgQnRoRM9KAuKXOweGnizEnwsqssuwFoV00gqiwdv9c 
  publishable:
    key: pk_test_51RXlPKQ6JcV4ZCjF1vl3NeGmma3hKAnfSGEKpULi1MYwVyduiUhViG3Dkdvdhl9IOhe6AkzlKgbyNUJGXumc2XLs00qULacej6