package com.example.stage24.user.domain;

public enum AccessType {

    ARTICLE_FETCH,
    ARTICLE_UPDATE,
    ARTICLE_CREATE,
    ARTICLE_DELETE,

    REVIEW_FETCH,
    REVIEW_UPDATE,
    REVIEW_CREATE,
    REVIEW_DELETE,

    CATEGORY_FETCH,
    CATEGORY_UPDATE,
    CATEGORY_CREATE,
    CATEGORY_DELETE,

    INVOICE_FETCH,
    INVOICE_CREATE,
    INVOICE_DELETE

    }
