spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pfe2025
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 256MB
      max-request-size: 256MB
      enabled: true

application:
  security:
    jwtSecret: I12OI3N12IONOIEN12IONEIO12JOI312KLNEOKZAKLHEIHO21IN3KL1N2LKNDIOI12OI3N12IONOIEN12IONEIO12JOI312KL
    jwtExpirationMs: 86400000
    jwtRefreshExpirationMs: 8640000

logging:
  level:
    org.springframework.security.web: DEBUG

upload:
  dir: classpath:/assets/images

# Stripe Configuration
stripe:
  secret:
    key: sk_test_51RXlPKQ6JcV4ZCjFQbwDeEqDlhyMyukOGkpDcr8ZXONpc3V8DTUVCNWRgQnRoRM9KAuKXOweGnizEnwsqssuwFoV00gqiwdv9c # Replace with your actual Stripe secret key
  publishable:
    key: pk_test_51RXlPKQ6JcV4ZCjF1vl3NeGmma3hKAnfSGEKpULi1MYwVyduiUhViG3Dkdvdhl9IOhe6AkzlKgbyNUJGXumc2XLs00qULacej6 # Replace with your actual Stripe publishable key
  # webhook:
  #   secret: whsec_1234567890abcdef # Replace with your actual webhook secret